### ISSUE TITLE
Limit number of pulls over time period

### ISSUE THREAD

**Issue by csmith** [greboid/dockermirror#1]
The current implementation will mirror all repos in one go every $DURATION, which is going to start causing problems when Docker Hub enforces really low pull limits.

I'd like to be able to spread the mirror pulls out over a wider time. I think two approaches would work:

1) Stagger all pulls so they are distributed across the entire $DURATION (i.e., if there are n pulls configured, after each one sleep for 1/nth the length of $DURATION). I could then set the duration to e.g. 1 day, and the hits would be spread over four of Docker Hub's 6 hour windows.

2) Add a separate config setting to limit the number of pulls per run (and then when it runs again after $DURATION continue from the point it left off).

**Comment by greboid** [comment]
I think the new rate limit option should probably cover this fully now
